name : First Workflow
on : [push]

jobs:
  runs-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run : echo "Hellow World!"
      - name: Multiline runs-shell-commands
        run: |
          node -v
          npm -v